import type { NextPage } from 'next'
import { Grid } from '@material-ui/core'
import { LeftImageLogin } from '../components/leftImageLogin/leftImageLogin'
import { LoginForm } from '../components/loginForm/LoginForm'

const LoginPage : NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Meus Bitcons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        spacing={3}
        justifyContent="space-between"
        alignItems="center"
      >
        <Grid item xs={8}>
          <h1>Bem vindo!</h1>
        </Grid>
        <Grid item xs={12} sm={6}>
          <LeftImageLogin />
        </Grid>
        <Grid
          container
          item
          xs={4}
          justifyContent="flex-end"
        >
          <Button
            variant="contained"
            size="large"
            style={{ background: 'var(--bg-primary)', color: 'white' }}
            onClick={() => setOpenForm(!openForm)}
          >
            Nova Transação
          </Button>
        </Grid>
      </Grid>
      <Grid container spacing={3}>
        <Grid item xs={3}>
          <InfoCard
            title="Total Investido"
            value="R$ 11.501,55"
            type="error"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="Rendimento"
            value="R$ 985,75"
            type="success"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="% de Retorno"
            value="8,57 %"
            type="primary"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="Cotação Atual"
            value="R$ 346.589,37"
            type="warning"
          />
        </Grid>

        <Grid item xs={12}>
          <Chart data={data} />
        </Grid>

        <Grid item xs={12}>
          <Table />
        </Grid>
      </Grid>
      <Grid container item xs={12} sm={6} style={{padding: 10}}>
        <LoginForm />
      </Grid>
    </Grid>
  )
}

export default LoginPage