import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Container, Grid } from '@material-ui/core'

import InfoCard from '../components/cards/InfoCard'
import Modal from '../components/modals/Modal'
import Chart from '../components/charts/Chart'
import TransactionForm from '../components/forms/TransactionForm'
import Table from '../components/tables/Table'
import apiBtc, { apiCotation } from '../services/apiBtc'

const dataChart = [
  { argument: 1, value: 5 },
  { argument: 2, value: 2 },
  { argument: 3, value: 5 },
  { argument: 4, value: 5 },
  { argument: 5, value: 8 },
];
interface TransactionResponseInterface {
  id?: number
  quantity?: number
  transaction_date?: string
  userId?: number
  value_buy?: number
  crypto_type?: string
}
const Home: NextPage = () => {
  const [openForm, setOpenForm] = useState(false)
  const [transactions, setTransactions] = useState([])
  const [cotation, setCotation] = useState(0)
  const [total, setTotal] = useState(0)
  const [dataForm, setDataForm] = useState(null)

  const getTransactions = async () => {
    await apiBtc.get('/transaction')
      .then(response => {
        const data: TransactionResponseInterface[] = response.data?.map((transaction: any) => ({
          id: transaction.id,
          data: transaction.transaction_date,
          cotacao: transaction.value_buy,
          compra: transaction.quantity * transaction.value_buy,
          total: transaction.quantity
        }))

        const total = data.reduce((acc, act) => acc + act.compra, 0)
        setTotal(total.toFixed(2))        
        
        setTransactions(data)
      })
  }
  const getCotation = async () => {
    const params = {
      ids: 'bitcoin',
      vs_currencies: 'brl'
    }
    await apiCotation.get('/price', {params})
      .then(response => {
        setCotation(response.data[params.ids].brl)
      })
  }

  const handleEdit = (data) => {
    setDataForm(data)
    setOpenForm(true)   
  }

  useEffect(() => {
    getTransactions()
    getCotation()
  }, [])

  return (
    <Container>
      <Head>
        <title>Meus Bitcons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        spacing={3}
        justifyContent="space-between"
        alignItems="center"
      >
        <Grid item xs={8}>
          <h1>Bem vindo!</h1>
        </Grid>
        <Grid
          container
          item
          xs={4}
          justifyContent="flex-end"
        >
          <Button
            variant="contained"
            size="large"
            style={{ background: 'var(--bg-primary)', color: 'white' }}
            onClick={() => setOpenForm(!openForm)}
          >
            Nova Transação
          </Button>
        </Grid>
      </Grid>
      <Grid container spacing={3}>
        <Grid item xs={3}>
          <InfoCard
            title="Total Investido"
            value={total}
            type="error"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="Rendimento"
            value="R$ 985,75"
            type="success"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="% de Retorno"
            value="8,57 %"
            type="primary"
          />
        </Grid>
        <Grid item xs={3}>
          <InfoCard
            title="Cotação Atual"
            value={cotation}
            type="warning"
          />
        </Grid>

        <Grid item xs={6}>
          <Chart data={dataChart} />
        </Grid>

        <Grid item xs={6}>
          <Table
            values={transactions}
            editCallback={handleEdit}
          />
        </Grid>
      </Grid>

      <Grid container spacing={3}>
        <Grid item xs={12}>
          <Modal
            title="Nova Transação"
            open={openForm}
          >
            <TransactionForm setOpenForm={setOpenForm} defaultValues={dataForm} />
          </Modal>
        </Grid>
      </Grid>
    </Container>
  )
}

export default Home
